name: "Terraform Application Pipeline"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment (dev/staging/prod)"
        required: true
        type: choice
        default: "dev"
        options:
          - "dev"
          - "test"
      action:
        description: "Action to perform (apply/destroy)"
        required: true
        type: choice
        default: "apply"
        options:
          - "apply"
          - "destroy"

env:
  TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}    

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app-tf
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform fmt
      - name: Terraform Apply/Destroy
        run: |
          if [ "${{ github.event.inputs.action }}" = "apply" ] then;
            terraform apply -auto-approve -var-file="variables/${{ github.event.inputs.environment }}.tfvars.json"
          else
            terraform destroy -auto-approve -var-file="variables/${{ github.event.inputs.environment }}.tfvars.json"
          fi